version: '3.9'

services:

  api:
    image: rbecamb/via-appia:v4
    container_name: via-appia-api
    ports:
      - '8000:8000'
    environment:
        URL_API_SS: https://supersapiensbackend.agu.gov.br
        LOG_LEVEL: info

    restart: always
